### ISSUE TITLE
L1 componet has no value

### ISSUE THREAD

**Issue by mdede439** [astuder/icp-101xx#10]
I was looking into building your boards and found there is no value defined for the L1 component in your schematic.  Can you let me know what it is?

**Comment by astuder** [comment]
L1 is a ferrite bead, like for example BLM18PG221SN1D for 0603 or BLM15PX221SN1D for 0402 footprint.

They are for noise suppression, but probably overkill anyways. Replacing them with a 0 ohm resistor will work too.

**Comment by mdede439** [comment]
Great!  Thanks for the info. Appreciate it.

Michael D

**Comment by astuder** [comment]
Added the part number to the schematics.
