### ISSUE TITLE
Error in formula for pressure calculation

### ISSUE THREAD

**Issue by CSC-Olivier** [astuder/icp-101xx#3]
Thanks @astuder  for the library!
Looking at the datasheet, it seems that there is a mistake in the way you calculate t.
In the datasheet, (page 20): t = _raw_t - 32768
In the library you have:  t = -45.f + 175.f / 65536.f * _raw_t.

**Comment by astuder** [comment]
Which datasheet are you referring to?
http://www.invensense.com/wp-content/uploads/2018/01/DS-000186-ICP-101xx-v1.0.pdf
page 20: *temperature = -45.f + 175.f/65536.f * T_LSB

**Comment by astuder** [comment]
Oh, I see: t as used in the pressure calculation should only be t = _raw_t - 32768. And the conversion to actual temperature should only be at the end of the calculation.

Thanks for reporting!

**Comment by CSC-Olivier** [comment]
sure!
Thanks for making the library

**Comment by astuder** [comment]
Fixed.

This part of the formula probably compensates for temperature when measuring pressure. The difference before and after the fix is very small (6-7Pa at 20C).
