### ISSUE TITLE
_raw_p calculation on 8bit MCUs

### ISSUE THREAD

**Issue by CSC-Olivier** [astuder/icp-101xx#4]
When using the library, (arduino version 1.8.5 with an atmega328pb), I had some issues with the _raw_p initial reading form res_buf. Because res_buf are uint8_t there were some issue with the bit shift and the result was incorrect.
here is what I changed to make it work:
```
	uint32_t L_res_buf3 = res_buf[3];
	uint32_t L_res_buf4 = res_buf[4];
	uint32_t L_res_buf6 = res_buf[6];
	_raw_p = (L_res_buf3 << 16) | (L_res_buf4 << 8) | L_res_buf6;
```

**Comment by astuder** [comment]
Thanks! I will look into this later this week. I only used the library with ARM M0 based boards yet.

**Comment by CSC-Olivier** [comment]
Also, the compiler was struggling with _lut_lower and _lut_upper definition. I replaced them with their actual value 3670016.0 and 12058624.0 respectively and it works.

**Comment by astuder** [comment]
The trick is probably, to cast all integers to 32bit before shifting them around. The AVR compiler probably defaults to 16 bit.
