### ISSUE TITLE
Simple question

### ISSUE THREAD

**Issue by Air16** [astuder/icp-101xx#5]
Hello Adrian,

The sensor plot image you recorded is quite amazing !

Was is FAST, NORMAL, ACCURATE or VERY_ACCURATE mode ?

During the "almost static" horizontal phases, were was the device ? Was it in your hand or placed on a table ?

Thank you !

**Comment by astuder** [comment]
FAST, NORMAL, ACCURATE and VERY ACCURATE are more user friendly (Arduino friendly) words for Low Power, Normal, Low Noise and Ultra Low Noise conversion modes described in the [datasheet](https://www.invensense.com/download-pdf/icp-101xx-datasheet/). See chapter 2.2, page 6.

The sensor breakout board was mounted on a small breadboard, placed on a desk. For the slow/fast elevation change in the 2nd half of the graph, I picked up the breadboard by hand. The 0.1C temperature change is probably radiated heat from my hand in close proximity to the sensor.

**Comment by Air16** [comment]
ok thanks.
My first question was to know which of those modes (FAST, NORMAL...) did you use for your test ?

**Comment by astuder** [comment]
I don't remember, but it was probably VERY_ACCURATE. 

One thing to note: In my home (60's wooden construction with bad insulation) the pressure reading is not as stable as in the graph when it's windy outside. There will be similar effects when an AC is running.

**Comment by Air16** [comment]
ok thanks
