### ISSUE TITLE
Populated breakout boards

### ISSUE THREAD

**Issue by pmoma** [astuder/icp-101xx#7]
Hi Adrian,
Thanks for creating these resources, I am a graduate student at the University of Arizona working on a project that I want to use the ICP-10100 in and the arduino library and pcb diagram has been very helpful.  I am interested in getting populated breakout boards from you and was also wondering if you would be willing to work with me to tweak the breakout board to put the sensor onto a flexpcb with an even smaller overall profile than the current board in order to fit it in an even smaller space than the current one can- like the orange pcbs in this image: https://media.digikey.com/Photos/Sensirion/EK-H5-1.8V.jpg

Thanks a lot!
Peter Moma

**Comment by astuder** [comment]
That's an interesting idea! I never created flexpcbs, but this would be a good excuse to give it a try.

What size (sensor area/volume, length of the tail, connector pitch) do you have in mind? Would it be ok to have the LDO and level conversion still on the flex, but close to the connector?

**Comment by astuder** [comment]
Looking at the picture on Digi-key, I guess LDO and level conversion could sit on an adapter board.

**Comment by pmoma** [comment]
Thanks for the quick reply! My thought was essentially to run it just as you had built it, using the adapter board just as is but replacing the break away piece with a flexpcb, and only having the capacitor, ferrite, and sensor on the flex.  As fas as size, I was thinking like a 60 mmx2-3mm board, narrow is important but length is flexible.  I am trying to measure the pressure inside of a gas probe and it is a very narrow space so really just the thinner the better.  And for connectors I figured I would just solder a jumper wire from the flexpcb pad to the adapter board.

**Comment by astuder** [comment]
Sounds like a plan. I can whip something up this weekend.

**Comment by pmoma** [comment]
Sorry I missed this that would be great! And do you assemble the boards yourself or have them made by a pcba company?  I am by no means an electrical engineer, but I opened the Kicad files and I can see that there are values to specify what the parts are I just have no idea how one would translate that to a pcba company.

**Comment by astuder** [comment]
If it's just a hand-full of units, I usually assemble them manually and reflow in a toaster oven. Happy to do that for you. Drop me an email to the email address on my Github profile if interested.

**Comment by astuder** [comment]
Something like this?
![image](https://user-images.githubusercontent.com/1166488/67642527-d8beab00-f8c9-11e9-8235-b1fbae429102.png)

**Comment by pmoma** [comment]
Wow!! Yes that is awesome, in this format would the adapter board also be a flexpcb?  It doesn't have to be particularly rugged so that would be fine and I assume it can't be half and half anyways.  Also I was looking at PCB reflow ovens but a toaster seems way easier thats a good idea.  Thanks a bunch I'll shoot you an email!

**Comment by AufBager** [comment]
I'd be interested to know if anyone has run into problems with this PCB layout as we have several hundred on hand, but we've been running into intermittent data issues with I2C. Is there any chance of data issues when it comes to those long straight data traces? We also encapsulate the top components in resin so that may be shifting/pulling some of the SMD components.

**Comment by astuder** [comment]
I didn't run into problems, but I didn't use these for more than simple experiments.

One possibility is, that the the pull-up resistors are a bit too weak, especially with the sensor running at 1.8V. Did you already try running I2C at a slower speed?
